package audit

import (
	"errors"
	"fmt"

	"ai-gateway/internal/models"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// MaintenanceKind identifies one of the two approved offline maintenance
// operations. The kind is caller-selectable; all audit identities are fixed by
// the maintenance module.
type MaintenanceKind string

const (
	MaintenanceKindProviderSecretMigration MaintenanceKind = "migrate-provider-secrets"
	MaintenanceKindRequestLogScrub         MaintenanceKind = "scrub-request-log-content"
)

// MaintenanceOperation is the trusted correlation returned by BeginMaintenanceTx.
// TargetID is generated by this package and must match a verified pending STARTED
// event before CompleteMaintenanceTx can append SUCCESS.
type MaintenanceOperation struct {
	Kind          MaintenanceKind
	ActorType     string
	ActorID       string
	TargetType    string
	TargetID      string
	StartedAction string
	SuccessAction string
}

type maintenanceSpec struct {
	kind          MaintenanceKind
	actorType     string
	actorID       string
	startedAction string
	successAction string
}

var maintenanceSpecs = [...]maintenanceSpec{
	{
		kind:          MaintenanceKindProviderSecretMigration,
		actorType:     "cli",
		actorID:       "migrate-provider-secrets",
		startedAction: ActionProviderSecretMigrationStarted,
		successAction: ActionProviderSecretMigration,
	},
	{
		kind:          MaintenanceKindRequestLogScrub,
		actorType:     "cli",
		actorID:       "scrub-request-log-content",
		startedAction: ActionRequestLogScrubStarted,
		successAction: ActionRequestLogScrub,
	},
}

type maintenanceState struct {
	spec      maintenanceSpec
	started   *models.AuditEvent
	completed bool
}

func maintenanceSpecForKind(kind MaintenanceKind) (maintenanceSpec, bool) {
	for _, spec := range maintenanceSpecs {
		if spec.kind == kind {
			return spec, true
		}
	}
	return maintenanceSpec{}, false
}

func maintenanceSpecForAction(action string) (maintenanceSpec, bool) {
	for _, spec := range maintenanceSpecs {
		if spec.startedAction == action || spec.successAction == action {
			return spec, true
		}
	}
	return maintenanceSpec{}, false
}

func maintenanceActions() []string {
	actions := make([]string, 0, len(maintenanceSpecs)*2)
	for _, spec := range maintenanceSpecs {
		actions = append(actions, spec.startedAction, spec.successAction)
	}
	return actions
}

func maintenanceOperation(spec maintenanceSpec, targetID string) MaintenanceOperation {
	return MaintenanceOperation{
		Kind:          spec.kind,
		ActorType:     spec.actorType,
		ActorID:       spec.actorID,
		TargetType:    "maintenance-operation",
		TargetID:      targetID,
		StartedAction: spec.startedAction,
		SuccessAction: spec.successAction,
	}
}

func validateMaintenanceEvent(event models.AuditEvent, spec maintenanceSpec) error {
	if event.ActorType != spec.actorType ||
		event.ActorID != spec.actorID ||
		event.TargetType != "maintenance-operation" ||
		event.Reason != "" {
		return ErrAuditIntegrity
	}
	parsed, err := uuid.Parse(event.TargetID)
	if err != nil || parsed.String() != event.TargetID {
		return ErrAuditIntegrity
	}
	return nil
}

func requireActiveMaintenanceTransaction(tx *gorm.DB) error {
	if tx == nil || tx.Statement == nil {
		return ErrAuditTransactionRequired
	}
	if _, ok := tx.Statement.ConnPool.(activeSQLTransaction); !ok {
		return ErrAuditTransactionRequired
	}
	if err := tx.Exec("SELECT 1").Error; err != nil {
		if errors.Is(normalizeAuditDBError(err), ErrAuditTransactionRequired) {
			return ErrAuditTransactionRequired
		}
		return normalizeAuditDBError(err)
	}
	return nil
}

func loadMaintenanceStates(tx *gorm.DB) (map[MaintenanceKind]map[string]*maintenanceState, error) {
	var events []models.AuditEvent
	if err := tx.Where("action IN ?", maintenanceActions()).Order("id ASC").Find(&events).Error; err != nil {
		return nil, auditIntegrityError("maintenance history unavailable")
	}

	states := make(map[MaintenanceKind]map[string]*maintenanceState, len(maintenanceSpecs))
	targetKinds := make(map[string]MaintenanceKind)
	for _, spec := range maintenanceSpecs {
		states[spec.kind] = make(map[string]*maintenanceState)
	}
	for index := range events {
		event := &events[index]
		spec, ok := maintenanceSpecForAction(event.Action)
		if !ok || validateMaintenanceEvent(*event, spec) != nil {
			return nil, ErrAuditIntegrity
		}
		if priorKind, exists := targetKinds[event.TargetID]; exists && priorKind != spec.kind {
			return nil, ErrAuditIntegrity
		}
		targetKinds[event.TargetID] = spec.kind

		byTarget := states[spec.kind]
		state := byTarget[event.TargetID]
		if state == nil {
			state = &maintenanceState{spec: spec}
			byTarget[event.TargetID] = state
		}
		switch event.Action {
		case spec.startedAction:
			if state.started != nil || state.completed {
				return nil, ErrAuditIntegrity
			}
			state.started = event
		case spec.successAction:
			if state.started == nil || state.completed {
				return nil, ErrAuditIntegrity
			}
			state.completed = true
		default:
			return nil, ErrAuditIntegrity
		}
	}
	return states, nil
}

func pendingMaintenanceOperations(states map[MaintenanceKind]map[string]*maintenanceState) ([]MaintenanceOperation, error) {
	var pending []MaintenanceOperation
	for _, spec := range maintenanceSpecs {
		for targetID, state := range states[spec.kind] {
			if state.started != nil && !state.completed {
				if err := validateMaintenanceEvent(*state.started, spec); err != nil {
					return nil, err
				}
				pending = append(pending, maintenanceOperation(spec, targetID))
			}
		}
	}
	if len(pending) > 1 {
		return nil, ErrAuditIntegrity
	}
	return pending, nil
}

// BeginMaintenanceTx begins or resumes one fixed maintenance operation inside
// the caller's active transaction. The chain-state no-op UPDATE is deliberately
// before all maintenance-history reads, so SQLite serializes pending lookup and
// STARTED creation across independent database handles.
func (s *Service) BeginMaintenanceTx(tx *gorm.DB, kind MaintenanceKind) (MaintenanceOperation, error) {
	spec, ok := maintenanceSpecForKind(kind)
	if !ok {
		return MaintenanceOperation{}, fmt.Errorf("audit: unknown maintenance kind")
	}
	if err := requireActiveMaintenanceTransaction(tx); err != nil {
		return MaintenanceOperation{}, err
	}
	if err := acquireChainWriteLock(tx); err != nil {
		return MaintenanceOperation{}, err
	}
	if err := verifyAuditChainDB(tx); err != nil {
		return MaintenanceOperation{}, err
	}
	states, err := loadMaintenanceStates(tx)
	if err != nil {
		return MaintenanceOperation{}, err
	}
	pending, err := pendingMaintenanceOperations(states)
	if err != nil {
		return MaintenanceOperation{}, err
	}
	if len(pending) == 1 {
		if pending[0].Kind != kind {
			return MaintenanceOperation{}, ErrAuditIntegrity
		}
		return pending[0], nil
	}

	operation := maintenanceOperation(spec, uuid.NewString())
	if err := s.RecordTx(tx, models.AuditEvent{
		Action:     spec.startedAction,
		ActorType:  spec.actorType,
		ActorID:    spec.actorID,
		TargetType: operation.TargetType,
		TargetID:   operation.TargetID,
		Reason:     "",
	}); err != nil {
		return MaintenanceOperation{}, err
	}
	return operation, nil
}

// CompleteMaintenanceTx appends the fixed success action for a verified
// pending operation. The caller-provided identity is only a correlation claim;
// the target written to SUCCESS comes from the pending STARTED event.
func (s *Service) CompleteMaintenanceTx(tx *gorm.DB, operation MaintenanceOperation) error {
	if err := requireActiveMaintenanceTransaction(tx); err != nil {
		return err
	}
	spec, ok := maintenanceSpecForKind(operation.Kind)
	if !ok || operation != maintenanceOperation(spec, operation.TargetID) {
		return ErrAuditIntegrity
	}
	if err := acquireChainWriteLock(tx); err != nil {
		return err
	}
	if err := verifyAuditChainDB(tx); err != nil {
		return err
	}
	states, err := loadMaintenanceStates(tx)
	if err != nil {
		return err
	}
	pending, err := pendingMaintenanceOperations(states)
	if err != nil {
		return err
	}
	if len(pending) != 1 || pending[0].Kind != operation.Kind || pending[0].TargetID != operation.TargetID {
		return ErrAuditIntegrity
	}
	return s.RecordTx(tx, models.AuditEvent{
		Action:     spec.successAction,
		ActorType:  spec.actorType,
		ActorID:    spec.actorID,
		TargetType: "maintenance-operation",
		TargetID:   pending[0].TargetID,
		Reason:     "",
	})
}
